name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # install setup.py
        pip install .
        pip install pycodestyle
        pip install pylint
    - name: Lint with pycodestyle - will fail and stop on any issues!
      run: |
        pycodestyle covid19_graphs
    - name: pylint on code directory. N.B. always passes! Please check log below for issues.
      run: |
        pylint --exit-zero -d logging-fstring-interpolation,logging-format-interpolation covid19_graphs/*.py
    - name: pylint on tests. Please check log below for issues.
      run: |
        # for tests ignore docstring
        pylint --exit-zero -d missing-docstring covid19_graphs/tests/*.py
    - name: Test with pytest
      run: |
        pytest -v
